### ISSUE TITLE
Boss Disappearance

### ISSUE THREAD

**Issue by Jindeathwalk** [3snowp7im/SotN-Randomizer#1]
Hi,

I did two runs a few hours ago and a lot of bosses wasn't in the game, it was the same in the two runs with two different seeds:

- Doppel 10
- Colosseum Combo
- Scylla
- Cerberus
- Olrox
- Richter (Fight skipped to the cutscene like a classic Richter Skip)
- The Creature
- Medusa
- Death (not sure)

I didn't check Hippogryph, Legion, Akmodan, Doppel 40, Galamoth, Trevor & Co and Beelzebuth.
I dunno if it was voluntary or not (because there was no info about it).

I have one of the two seeded file (deleted the 1st one during stream and didn't copy the seeds, sorry) in case you need it, I can create a wetransfer link and send it on discord.

Thanks for your work, item rando is cool (even if we get a lot of usable at the beginning we can make good time haha) and good luck !

**Comment by 3snowp7im** [comment]
This is bug caused by the Maria cutscene skip I attempted to implement yesterday. I reverted the change earlier today, but you must have created the seeds before I found the bug. I'm still working on how to skip the cutscene correctly, but I'm closing this issue because the commit that caused it has already been reverted.
